trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: kv-secrets

steps:

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

# Login to Azure using Service Connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'terraform-sp'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      echo "Initializing Terraform..."
      terraform init

      echo "Running Terraform Plan..."
      terraform plan \
        -var "vm_username=$(vm-username)" \
        -var "vm_password=$(vm-password)"

      echo "Applying Terraform..."
      terraform apply -auto-approve \
        -var "vm_username=$(vm-username)" \
        -var "vm_password=$(vm-password)"
